<?php
/**
 * Single Blog Post Template — PetZenAI
 */
get_header();
the_post();

$author   = get_the_author();
$date     = get_the_date('F j, Y');
$cat      = get_the_category();
$cat_name = $cat ? $cat[0]->name : 'Pet Health';
$cat_link = $cat ? get_category_link($cat[0]->term_id) : home_url('/blog/');
$read_min = max(1, ceil(str_word_count(strip_tags(get_the_content())) / 200));
?>

<!-- Single Post Hero (merged with featured image, when one exists) -->
<?php $hero_img_url = has_post_thumbnail() ? get_the_post_thumbnail_url(get_the_ID(), 'petzenai-hero') : ''; ?>
<div class="pz-single-hero<?php echo $hero_img_url ? ' has-img' : ''; ?>"
     <?php if($hero_img_url): ?>style="background-image:url('<?php echo esc_url($hero_img_url); ?>')"<?php endif; ?>>
  <?php if($hero_img_url): ?>
  <div class="pz-single-hero-overlay" aria-hidden="true"></div>
  <?php endif; ?>
  <div class="pz-single-hero-bg" aria-hidden="true"></div>
  <div class="container pz-single-hero-inner">
    <!-- Breadcrumb -->
    <nav class="pz-single-breadcrumb" aria-label="Breadcrumb"
         itemscope itemtype="https://schema.org/BreadcrumbList">
      <span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <a href="<?php echo home_url('/'); ?>" itemprop="item"><span itemprop="name">Home</span></a>
        <meta itemprop="position" content="1">
      </span>
      <span aria-hidden="true">›</span>
      <span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <a href="<?php echo esc_url($cat_link); ?>" itemprop="item"><span itemprop="name"><?php echo esc_html($cat_name); ?></span></a>
        <meta itemprop="position" content="2">
      </span>
      <span aria-hidden="true">›</span>
      <span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <span itemprop="name"><?php the_title(); ?></span>
        <meta itemprop="position" content="3">
      </span>
    </nav>

    <div class="pz-single-meta">
      <span class="pz-post-cat"><?php echo esc_html($cat_name); ?></span>
      <span class="pz-post-meta-item">📅 <?php echo $date; ?></span>
      <span class="pz-post-meta-item">⏱️ <?php echo $read_min; ?> min read</span>
    </div>

    <h1 class="pz-single-title"><?php the_title(); ?></h1>

    <?php if(has_excerpt()): ?>
    <p class="pz-single-excerpt"><?php the_excerpt(); ?></p>
    <?php endif; ?>

    <div class="pz-single-author-bar">
      <div class="pz-author-avatar" aria-hidden="true">🐾</div>
      <div>
        <span class="pz-author-name"><?php echo esc_html($author); ?></span>
        <span class="pz-author-role">PetZenAI Editorial Team · Vet-Reviewed</span>
      </div>
    </div>
  </div>
  <?php if($hero_img_url): // hidden real <img> so it still counts as itemprop=image, alt text, SEO/accessibility ?>
  <img src="<?php echo esc_url($hero_img_url); ?>" alt="<?php echo esc_attr(get_the_title().' — PetZenAI'); ?>" itemprop="image" style="position:absolute;width:1px;height:1px;overflow:hidden;opacity:0" loading="eager">
  <?php endif; ?>
</div>

<!-- Article Content -->
<article class="pz-single-article" itemscope itemtype="https://schema.org/Article">
  <meta itemprop="headline"      content="<?php the_title_attribute(); ?>">
  <meta itemprop="datePublished" content="<?php echo get_the_date('c'); ?>">
  <meta itemprop="dateModified"  content="<?php echo get_the_modified_date('c'); ?>">
  <meta itemprop="author"        content="<?php echo esc_attr($author); ?>">

  <div class="container pz-single-layout">

    <!-- Main Content -->
    <div class="pz-single-content" itemprop="articleBody">

      <!-- Ad: Blog Post Top -->
      <?php petzenai_ad( 'petzenai_adsense_ad_blog_top', 'blog-top' ); ?>

      <!-- Table of Contents (auto-generated by JS) -->
      <details class="pz-toc" id="pz-toc" hidden>
        <summary class="pz-toc-title">📋 Table of Contents</summary>
        <ul id="pz-toc-list"></ul>
      </details>

      <?php the_content(); ?>

      <!-- Tags -->
      <?php $tags = get_the_tags(); if($tags): ?>
      <div class="pz-post-tags" aria-label="Post tags">
        <span class="pz-tags-label">🏷️ Tags:</span>
        <?php foreach($tags as $tag): ?>
        <a href="<?php echo get_tag_link($tag->term_id); ?>" class="pz-tag-chip">
          <?php echo esc_html($tag->name); ?>
        </a>
        <?php endforeach; ?>
      </div>
      <?php endif; ?>

      <!-- Share -->
      <div class="pz-share-bar">
        <span class="pz-share-label">Share this article:</span>
        <?php
        $share_url   = urlencode(get_permalink());
        $share_title = urlencode(get_the_title());
        $socials = [
          ['Facebook', 'https://www.facebook.com/sharer/sharer.php?u=' . $share_url, '📘'],
          ['Twitter',  'https://twitter.com/intent/tweet?text=' . $share_title . '&url=' . $share_url, '🐦'],
          ['Pinterest','https://pinterest.com/pin/create/button/?url=' . $share_url . '&description=' . $share_title, '📌'],
        ];
        foreach($socials as $s): ?>
        <a href="<?php echo esc_url($s[1]); ?>" class="pz-share-btn" target="_blank" rel="noopener noreferrer"
           aria-label="Share on <?php echo $s[0]; ?>">
          <?php echo $s[2]; ?> <?php echo $s[0]; ?>
        </a>
        <?php endforeach; ?>
      </div>

      <!-- Author Bio Box (E-E-A-T Signal) -->
      <div class="pz-author-bio-box">
        <div class="pz-author-bio-avatar">🐾</div>
        <div class="pz-author-bio-content">
          <div class="pz-author-bio-header">
            <h3 class="pz-author-bio-name">PetZenAI Editorial Team</h3>
            <span class="pz-author-bio-badge">✅ Vet-Reviewed</span>
          </div>
          <p class="pz-author-bio-text">Our editorial team consists of certified pet care specialists, veterinary consultants, and animal health researchers. Every article is reviewed for accuracy against current veterinary guidelines before publishing. We are committed to providing science-backed, trustworthy pet care information.</p>
          <div class="pz-author-bio-tags">
            <span>🎓 Certified Pet Care Specialists</span>
            <span>🏥 Vet-Reviewed Content</span>
            <span>🔬 Science-Based Guides</span>
          </div>
        </div>
      </div>

      <!-- Ad: Blog Post Middle -->
      <?php petzenai_ad( 'petzenai_adsense_ad_blog_mid', 'blog-mid' ); ?>

      <!-- Tool CTA (inline) -->
      <div class="pz-inline-cta">
        <span class="pz-inline-cta-icon" aria-hidden="true">🐾</span>
        <div>
          <strong>Try Our Free Tool</strong><br>
          <span>Use our science-based calculators to put this advice into action instantly.</span>
        </div>
        <a href="<?php echo home_url('/tools/'); ?>" class="btn-primary" style="flex-shrink:0;padding:12px 24px;font-size:14px">
          See All Tools →
        </a>
      </div>

    </div><!-- /pz-single-content -->

    <!-- Sidebar -->
    <aside class="pz-single-sidebar" aria-label="Sidebar">

      <!-- Ad: Sidebar -->
      <?php petzenai_ad( 'petzenai_adsense_ad_sidebar', 'sidebar' ); ?>

      <!-- Author Box -->
      <div class="pz-sidebar-widget pz-author-box">
        <div class="pz-author-avatar-big" aria-hidden="true">🐾</div>
        <h3 class="pz-author-box-name"><?php echo esc_html($author); ?></h3>
        <p class="pz-author-box-bio">PetZenAI Editorial Team. All content is reviewed by veterinary nutritionists and animal health specialists.</p>
        <span class="pz-author-badge">✅ Vet-Reviewed Content</span>
      </div>

      <!-- Related Tools -->
      <div class="pz-sidebar-widget">
        <h3 class="pz-sidebar-title">🛠️ Free Pet Tools</h3>
        <?php
        $tools = [
          ['🍽️','Food Calculator','/tools/pet-food-portion-calculator/'],
          ['🎂','Age Calculator',  '/tools/pet-age-calculator/'],
          ['💉','Vaccine Tracker', '/tools/pet-vaccination-schedule/'],
          ['✨','Name Generator',  '/tools/ai-pet-name-generator/'],
          ['🏃','Exercise Planner','/tools/pet-exercise-calculator/'],
        ];
        foreach($tools as $t): ?>
        <a href="<?php echo home_url($t[2]); ?>" class="pz-sidebar-tool">
          <span class="pz-sidebar-tool-icon" aria-hidden="true"><?php echo $t[0]; ?></span>
          <span><?php echo $t[1]; ?></span>
          <span class="pz-sidebar-tool-arrow">→</span>
        </a>
        <?php endforeach; ?>
      </div>

      <!-- Related Posts -->
      <?php
      $related = new WP_Query([
        'posts_per_page'      => 3,
        'post__not_in'        => [get_the_ID()],
        'category__in'        => wp_get_post_categories(get_the_ID()),
        'post_status'         => 'publish',
        'ignore_sticky_posts' => true,
      ]);
      if($related->have_posts()): ?>
      <div class="pz-sidebar-widget">
        <h3 class="pz-sidebar-title">📚 Related Articles</h3>
        <?php while($related->have_posts()): $related->the_post(); ?>
        <a href="<?php the_permalink(); ?>" class="pz-related-item">
          <?php if(has_post_thumbnail()): the_post_thumbnail('thumbnail',['class'=>'pz-related-thumb','loading'=>'lazy','alt'=>esc_attr(get_the_title().' — PetZenAI')]); else: ?>
          <div class="pz-related-thumb-placeholder" aria-hidden="true">🐾</div>
          <?php endif; ?>
          <span><?php the_title(); ?></span>
        </a>
        <?php endwhile; wp_reset_postdata(); ?>
      </div>
      <?php endif; ?>

    </aside>
  </div>
</article>

<!-- More Articles -->
<section class="section section-alt" aria-label="More Articles">
  <div class="container">
    <div class="section-header" style="margin-bottom:40px">
      <span class="section-tag">Keep Reading</span>
      <h2 class="section-title" style="font-size:28px">More Pet Care <span>Guides</span></h2>
    </div>
    <div class="blog-grid">
      <?php
      $recent_posts = new WP_Query([
        'posts_per_page'      => 3,
        'post__not_in'        => [get_the_ID()],
        'post_status'         => 'publish',
        'orderby'             => 'date',
        'order'               => 'DESC',
        'ignore_sticky_posts' => true,
      ]);
      while($recent_posts->have_posts()): $recent_posts->the_post(); ?>
      <article class="blog-card" data-aos>
        <a href="<?php the_permalink(); ?>" class="blog-card-img-wrap">
          <?php if(has_post_thumbnail()): the_post_thumbnail('petzenai-thumb',['loading'=>'lazy']); else: ?>
          <img src="https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=600&q=80&auto=format&fit=crop"
               alt="<?php the_title_attribute(); ?>" loading="lazy" width="600" height="220">
          <?php endif; ?>
          <div class="blog-card-overlay" aria-hidden="true"></div>
        </a>
        <div class="blog-card-body">
          <span class="blog-card-cat"><?php echo get_the_category_list(', ') ?: 'Pet Health'; ?></span>
          <h3 class="blog-card-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
          <div class="blog-card-footer">
            <span class="blog-card-date">📅 <?php echo get_the_date('M j, Y'); ?></span>
            <a href="<?php the_permalink(); ?>" class="blog-read-more">Read →</a>
          </div>
        </div>
      </article>
      <?php endwhile; wp_reset_postdata(); ?>
    </div>
  </div>
</section>

<!-- Single Post CSS (inline for specificity) -->
<style>
.pz-single-hero{background:linear-gradient(135deg,#1A1A2E,#16213E);background-size:cover;background-position:center;padding:120px 0 60px;position:relative;overflow:hidden}
.pz-single-hero.has-img{padding:170px 0 70px}
.pz-single-hero-overlay{position:absolute;inset:0;background:linear-gradient(180deg,rgba(10,10,18,.55) 0%,rgba(10,10,18,.78) 55%,rgba(10,10,18,.94) 100%)}
.pz-single-hero-bg{position:absolute;inset:0;background:url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><text y="150" font-size="150" opacity="0.03">🐾</text></svg>') right bottom no-repeat;background-size:300px;pointer-events:none}
.pz-single-hero-inner{position:relative;z-index:1;max-width:860px}
@media(max-width:640px){.pz-single-hero.has-img{padding:130px 0 50px}}
.pz-single-breadcrumb{display:flex;flex-wrap:wrap;gap:6px;align-items:center;font-size:13px;color:rgba(255,255,255,0.5);margin-bottom:20px}
.pz-single-breadcrumb a{color:rgba(255,255,255,0.6);transition:color .2s}.pz-single-breadcrumb a:hover{color:var(--orange)}
.pz-single-meta{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-bottom:16px}
.pz-post-cat{background:var(--orange);color:#fff;padding:4px 14px;border-radius:50px;font-size:12px;font-weight:700}
.pz-post-meta-item{font-size:13px;color:rgba(255,255,255,0.55);font-weight:500}
.pz-single-title{font-size:clamp(26px,4vw,48px);font-weight:900;color:#fff;line-height:1.15;margin-bottom:16px}
.pz-single-excerpt{font-size:17px;color:rgba(255,255,255,0.7);line-height:1.7;margin-bottom:24px;max-width:720px}
.pz-single-author-bar{display:flex;align-items:center;gap:12px}
.pz-author-avatar{width:44px;height:44px;border-radius:50%;background:var(--orange);display:flex;align-items:center;justify-content:center;font-size:20px;flex-shrink:0}
.pz-author-name{font-weight:800;font-size:14px;color:#fff;display:block}
.pz-author-role{font-size:12px;color:rgba(255,255,255,0.5)}
.pz-single-article{padding:60px 0}
.pz-single-layout{display:grid;grid-template-columns:1fr 320px;gap:60px;max-width:1100px;align-items:start}
@media(max-width:900px){.pz-single-layout{grid-template-columns:1fr}}
.pz-single-content{min-width:0;max-width:720px}
.pz-single-content h2{font-size:25px;font-weight:900;color:#0D0D0D;margin:44px 0 18px;padding-top:24px;border-top:2px solid #F0F0F0;letter-spacing:-.01em;position:relative}
.pz-single-content h2::before{content:"";position:absolute;top:-2px;left:0;width:48px;height:2px;background:var(--orange)}
.pz-single-content h2:first-child{margin-top:0;padding-top:0;border-top:none}
.pz-single-content h2:first-child::before{display:none}
.pz-single-content h2 + p{font-size:18px;line-height:1.75;color:#1A1A1A;font-weight:500}
.pz-pullquote{font-size:21px;font-weight:800;color:#0D0D0D;line-height:1.5;border-left:4px solid var(--orange);padding:2px 0 2px 22px;margin:28px 0;letter-spacing:-.01em}
.pz-single-content h3{font-size:19px;font-weight:800;color:#0D0D0D;margin:26px 0 10px;line-height:1.35}
.pz-single-content p{font-size:16px;line-height:1.85;color:#3A3A3A;margin-bottom:18px}
.pz-single-content ul,.pz-single-content ol{margin:0 0 20px 20px;font-size:16px;line-height:1.85;color:#3A3A3A}
.pz-single-content li{margin-bottom:9px}
.pz-single-content table{width:100%;border-collapse:separate;border-spacing:0;margin:24px 0;font-size:14px;border-radius:14px;overflow:hidden;border:1px solid #EFEFEF;box-shadow:0 4px 16px -8px rgba(0,0,0,.12)}
.pz-single-content th{background:linear-gradient(135deg,#1A1A2E,#16213E);color:#fff;padding:14px 16px;text-align:left;font-size:12px;text-transform:uppercase;letter-spacing:.05em;font-weight:700}
.pz-single-content td{padding:14px 16px;border-bottom:1px solid #F0F0F0;vertical-align:top}
.pz-single-content tr:last-child td{border-bottom:none}
.pz-single-content tr:nth-child(even) td{background:#FAFAFA}
/* Dogs vs Cats comparison table — brand colors only (navy + orange, no off-palette hues) */
.pz-compare-table td.pz-col-sign{font-weight:800;color:#0D0D0D;white-space:nowrap}
.pz-compare-table th.pz-col-sign{color:#fff}
.pz-compare-table th.pz-col-dog{background:linear-gradient(135deg,#1A1A2E,#16213E)}
.pz-compare-table th.pz-col-cat{background:linear-gradient(135deg,#FF6B1A,#E55A0D)}
.pz-compare-table td:nth-child(2){border-left:3px solid #1A1A2E22}
.pz-compare-table td:nth-child(3){border-left:3px solid #FF6B1A33}
@media(max-width:900px){
  .pz-single-content table{display:block;overflow-x:auto}
  .pz-compare-table{display:block;overflow-x:visible;box-shadow:none;border:none}
  .pz-compare-table thead{display:none}
  .pz-compare-table tbody{display:block}
  .pz-compare-table tr{display:block;margin-bottom:12px;border-radius:14px;border:1px solid #EFEFEF;overflow:hidden;box-shadow:0 4px 16px -8px rgba(0,0,0,.12)}
  .pz-compare-table td{display:block;border-left:none!important;border-bottom:1px solid #F5F5F5;padding:10px 16px}
  .pz-compare-table td:last-child{border-bottom:none}
  .pz-compare-table td.pz-col-sign{background:linear-gradient(135deg,#1A1A2E,#16213E);color:#fff;font-size:13px;text-transform:uppercase;letter-spacing:.04em}
  .pz-compare-table td:not(.pz-col-sign)::before{content:attr(data-label);display:block;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.05em;color:var(--orange);margin-bottom:4px}
}
.pz-single-content a{color:var(--orange);font-weight:600;text-decoration:underline;text-underline-offset:2px}
.pz-single-content strong{font-weight:800;color:#0D0D0D}
.pz-single-content pre{background:#1A1A2E;color:#E8E8E8;padding:20px 24px;border-radius:14px;overflow-x:auto;font-size:14px;margin:20px 0;border-left:4px solid var(--orange)}
/* Numbered sign/step cards */
.pz-sign-card{display:flex;gap:16px;background:#FAFAFA;border:1px solid #EFEFEF;border-radius:16px;padding:20px 22px;margin-bottom:14px}
.pz-sign-num{flex-shrink:0;width:34px;height:34px;border-radius:50%;background:var(--orange);color:#fff;font-weight:900;font-size:14px;display:flex;align-items:center;justify-content:center;box-shadow:0 4px 10px -2px rgba(255,107,26,.5)}
.pz-sign-body{flex:1;min-width:0}
.pz-sign-body h3{margin:0 0 8px;font-size:17px}
.pz-sign-body p{font-size:15px;line-height:1.75;margin-bottom:12px}
.pz-sign-body p:last-child{margin-bottom:0}
.pz-sign-action{background:#fff;border-left:3px solid var(--orange);padding:9px 14px;border-radius:0 8px 8px 0;font-size:14px!important;color:#444}
@media(max-width:520px){.pz-sign-card{padding:16px}.pz-sign-num{width:28px;height:28px;font-size:13px}}
/* TOC — collapsed by default, click to open */
.pz-toc{background:#F7F7F7;border-radius:16px;padding:16px 24px;margin-bottom:32px;border:1.5px solid #E8E8E8}
.pz-toc[open]{padding-bottom:20px}
.pz-toc-title{font-size:14px;font-weight:800;color:#0D0D0D;text-transform:uppercase;letter-spacing:.04em;cursor:pointer;list-style:none;padding:8px 0}
.pz-toc-title::-webkit-details-marker{display:none}
.pz-toc-title::after{content:"▾";float:right;transition:transform .2s;color:var(--orange)}
.pz-toc[open] .pz-toc-title::after{transform:rotate(180deg)}
#pz-toc-list{margin:12px 0 0;padding-left:20px;columns:2;column-gap:24px}
#pz-toc-list li{margin-bottom:8px;break-inside:avoid}
#pz-toc-list a{color:var(--orange);font-size:14px;font-weight:600;text-decoration:none}
#pz-toc-list a:hover{text-decoration:underline}
@media(max-width:600px){#pz-toc-list{columns:1}}
/* Tags */
.pz-post-tags{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:32px 0 24px;padding-top:24px;border-top:2px solid #F0F0F0}
.pz-tags-label{font-size:13px;font-weight:700;color:#888}
.pz-tag-chip{background:#F0F0F0;color:#555;padding:5px 14px;border-radius:50px;font-size:13px;font-weight:600;transition:all .2s}
.pz-tag-chip:hover{background:var(--orange);color:#fff}
/* Author Bio Box */
.pz-author-bio-box{display:flex;gap:20px;background:linear-gradient(135deg,#F7F7F7,#FFF5F0);border:2px solid #FFE0CC;border-radius:20px;padding:28px;margin:36px 0;align-items:flex-start}
.pz-author-bio-avatar{width:72px;height:72px;border-radius:50%;background:linear-gradient(135deg,#FF6B1A,#e55a0d);display:flex;align-items:center;justify-content:center;font-size:32px;flex-shrink:0}
.pz-author-bio-content{flex:1;min-width:0}
.pz-author-bio-header{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:10px}
.pz-author-bio-name{font-size:18px;font-weight:900;color:#0D0D0D;margin:0}
.pz-author-bio-badge{background:rgba(76,175,80,.12);color:#2E7D32;border:1px solid rgba(76,175,80,.3);padding:4px 12px;border-radius:50px;font-size:12px;font-weight:700}
.pz-author-bio-text{font-size:14px;color:#555;line-height:1.7;margin:0 0 14px}
.pz-author-bio-tags{display:flex;flex-wrap:wrap;gap:8px}
.pz-author-bio-tags span{background:#fff;border:1px solid #E8E8E8;color:#666;padding:4px 12px;border-radius:50px;font-size:12px;font-weight:600}
@media(max-width:600px){.pz-author-bio-box{flex-direction:column;align-items:center;text-align:center}}
/* Share */
.pz-share-bar{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin-bottom:32px}
.pz-share-label{font-size:13px;font-weight:700;color:#888}
.pz-share-btn{padding:8px 18px;border:1.5px solid #E0E0E0;border-radius:50px;font-size:13px;font-weight:700;color:#333;transition:all .2s}
.pz-share-btn:hover{border-color:var(--orange);color:var(--orange)}
/* Inline CTA */
.pz-inline-cta{display:flex;align-items:center;gap:20px;background:linear-gradient(135deg,#1A1A2E,#16213E);border-radius:20px;padding:24px 28px;margin:32px 0;flex-wrap:wrap}
.pz-inline-cta-icon{font-size:36px;flex-shrink:0}
.pz-inline-cta strong{color:#fff;font-size:16px}
.pz-inline-cta span{color:rgba(255,255,255,0.6);font-size:14px}
/* Sidebar — compact */
.pz-single-sidebar{position:sticky;top:100px}
.pz-sidebar-widget{background:#fff;border:1.5px solid #F0F0F0;border-radius:16px;padding:16px;margin-bottom:16px}
.pz-sidebar-title{font-size:12px;font-weight:800;color:#0D0D0D;text-transform:uppercase;letter-spacing:.04em;margin-bottom:10px}
.pz-author-box{text-align:center;display:flex;align-items:center;gap:12px;text-align:left}
.pz-author-avatar-big{font-size:28px;margin-bottom:0;flex-shrink:0}
.pz-author-box-name{font-size:14px;font-weight:900;color:#0D0D0D;margin-bottom:2px}
.pz-author-box-bio{display:none}
.pz-author-badge{display:inline-block;background:rgba(76,175,80,.1);color:#2E7D32;padding:3px 10px;border-radius:50px;font-size:10.5px;font-weight:700}
.pz-sidebar-tool{display:flex;align-items:center;gap:8px;padding:6px 8px;border-radius:8px;font-size:13px;font-weight:600;color:#333;transition:all .2s;border:1px solid transparent}
.pz-sidebar-tool:hover{background:rgba(255,107,26,.06);border-color:var(--orange);color:var(--orange)}
.pz-sidebar-tool-icon{font-size:16px;flex-shrink:0}
.pz-sidebar-tool-arrow{margin-left:auto;opacity:0;transition:opacity .2s}
.pz-sidebar-tool:hover .pz-sidebar-tool-arrow{opacity:1}
.pz-related-item{display:flex;align-items:center;gap:10px;padding:7px 0;border-bottom:1px solid #F5F5F5;font-size:13px;font-weight:600;color:#333;transition:color .2s}
.pz-related-item:last-child{border-bottom:none}
.pz-related-item:hover{color:var(--orange)}
.pz-related-thumb{width:44px;height:34px;object-fit:cover;border-radius:6px;flex-shrink:0}
.pz-related-thumb-placeholder{width:44px;height:34px;background:#F0F0F0;border-radius:6px;display:flex;align-items:center;justify-content:center;flex-shrink:0}
@media(max-width:900px){.pz-single-sidebar{position:static}}
</style>

<script>
// Auto-generate Table of Contents
document.addEventListener('DOMContentLoaded', function() {
  var content = document.querySelector('.pz-single-content');
  var toc = document.getElementById('pz-toc');
  var list = document.getElementById('pz-toc-list');
  if(!content || !toc || !list) return;
  // Only top-level H2 sections (skips 15-signs sub-headings, FAQ questions,
  // and nested headings like the author bio box) so the TOC stays short.
  var headings = Array.prototype.filter.call(content.children, function(el){ return el.tagName === 'H2'; });
  if(headings.length < 3) return;
  headings.forEach(function(h, i) {
    if(!h.id) h.id = 'section-' + i;
    var li = document.createElement('li');
    li.innerHTML = '<a href="#' + h.id + '">' + h.textContent + '</a>';
    list.appendChild(li);
  });
  toc.hidden = false;
});
</script>

<?php get_footer(); ?>
